export const resources = [
  {
    app_name: 'Notify',
    short_description:
      'A simple app that keeps you up to date when a new transaction happens on your wallet.',
    category: 'App',
    author: 'carbonara',
    author_link: 'https://lisk.chat/direct/carbonara',
    app_images: ['https://s3.amazonaws.com/awesome-files/liskHunt/notify.jpg'],
    app_link: 'https://notifications.lisk.rocks',
    app_id: 'notify',
  },
  {
    app_name: 'lisk.builders',
    short_description: 'A community of developers with the interest for Lisk',
    category: 'Community',
    author: '5an1ty',
    author_link: 'https://lisk.chat/direct/5an1ty',
    app_images: [
      'https://s3.amazonaws.com/awesome-files/liskHunt/builders.jpg',
    ],
    app_link: 'https://lisk.builders',
    app_id: 'liskBuilders',
  },
  {
    app_name: 'DPOSTools',
    short_description: 'The Swiss-knife for major DPOS coins',
    category: 'App',
    author: 'vekexasia',
    author_link: 'https://lisk.chat/direct/vekexasia',
    app_images: [
      'https://s3.amazonaws.com/awesome-files/liskHunt/dpostools.jpg',
      'https://s3.amazonaws.com/awesome-files/liskHunt/dpos.jpg',
      'https://s3.amazonaws.com/awesome-files/liskHunt/dpos2.jpg',
      'https://s3.amazonaws.com/awesome-files/liskHunt/dpos3.jpg',
    ],
    app_link: 'https://dpostools.com/',
    app_id: 'DPOSTools',
  },
  {
    app_name: 'DelegatesBot',
    short_description: 'Telegram bot for you delegate',
    category: 'Bot',
    author: 'vekexasia',
    author_link: 'https://lisk.chat/direct/vekexasia',
    app_images: [
      'https://s3.amazonaws.com/awesome-files/liskHunt/delegatesbot.jpg',
    ],
    app_link: 'https://t.me/delegatesbot',
    app_id: 'delegatesbot',
  },
  {
    app_name: 'Lisk Monitor',
    short_description:
      'LiskMonitor is a stand-alone script to do end-user monitoring on Lisk Node(s) and Delegate.',
    category: 'Script',
    author: 'gr33ndrag0n',
    author_link: 'https://lisk.chat/direct/gr33ndrag0n',
    app_images: [
      'https://s3.amazonaws.com/awesome-files/liskHunt/delegateMonitor.jpg',
    ],
    app_link: 'https://github.com/Gr33nDrag0n69/LiskMonitor',
    app_id: 'liskmonitor',
  },
  {
    app_name: 'Liskit',
    short_description: 'The coolest DPOS Lisk platform pool',
    category: 'Pool',
    author: 'liskit',
    author_link: 'https://lisk.chat/direct/liskit',
    app_images: ['https://s3.amazonaws.com/awesome-files/liskHunt/liskit.jpg'],
    app_link: 'http://liskit.me/',
    app_id: 'liskit',
  },
  {
    app_name: 'Lisky',
    short_description: 'A command line interface for Lisk',
    category: 'LiskOfficial',
    author: 'LiskHQ',
    author_link: 'https://lisk.chat/direct/isabella',
    app_images: ['https://s3.amazonaws.com/awesome-files/liskHunt/lisky.jpg'],
    app_link: 'https://github.com/LiskHQ/lisky',
    app_id: 'lisky',
  },
  {
    app_name: 'liskpro',
    short_description: 'Pool & promotion in French',
    category: 'Pool',
    author: 'liskpro',
    author_link: 'https://lisk.chat/direct/LiskPro.com',
    app_images: ['https://s3.amazonaws.com/awesome-files/liskHunt/liskpro.jpg'],
    app_link: 'https://www.liskpro.com/',
    app_id: 'liskpro',
  },
  {
    app_name: 'Lisk-multiSigner',
    short_description:
      'Sign multiple pending multisig transactions automatically in one batch',
    category: 'Script',
    author: 'cc001',
    author_link: 'https://lisk.chat/direct/cc001',
    app_images: [
      'https://s3.amazonaws.com/awesome-files/liskHunt/LiskmultiSigner.jpg',
    ],
    app_link: 'https://github.com/simonmorgenthaler/Lisk-multiSigner',
    app_id: 'LiskmultiSigner',
  },
  {
    app_name: 'Liskpool',
    short_description: 'Open source Lisk Pool',
    category: 'Pool',
    author: 'karek',
    author_link: 'https://lisk.chat/direct/karek',
    app_images: [
      'https://s3.amazonaws.com/awesome-files/liskHunt/liskpool.jpg',
      'https://s3.amazonaws.com/awesome-files/liskHunt/liskpool2.jpg',
    ],
    app_link: 'https://github.com/karek314/liskpool',
    app_id: 'liskpool',
  },
  {
    app_name: 'Liskak',
    short_description:
      'Lisk Army Knife - Forging failover and command line lisk',
    category: 'Script',
    author: 'hmachado',
    author_link: 'https://lisk.chat/direct/hmachado',
    app_images: ['https://s3.amazonaws.com/awesome-files/liskHunt/liskak.jpg'],
    app_link: 'https://github.com/filipealmeida/liskak',
    app_id: 'liskak',
  },
  {
    app_name: 'Lisk Nano',
    short_description: 'The official desktop wallet for Lisk',
    category: 'LiskOfficial',
    author: 'LiskHQ',
    author_link: 'https://lisk.chat/direct/isabella',
    app_images: [
      'https://s3.amazonaws.com/awesome-files/liskHunt/lisknano.jpg',
    ],
    app_link: 'https://lisk.io/download',
    app_id: 'lisknano',
  },
  {
    app_name: 'Lisk Core',
    short_description: 'The core of Lisk.',
    category: 'LiskOfficial',
    author: 'LiskHQ',
    author_link: 'https://lisk.chat/direct/isabella',
    app_images: [
      'https://s3.amazonaws.com/awesome-files/liskHunt/liskcore.jpg',
    ],
    app_link: 'https://lisk.io/download',
    app_id: 'liskcore',
  },
  {
    app_name: 'Lisk-js',
    short_description: 'The core of Lisk.',
    category: 'LiskOfficial',
    author: 'LiskHQ',
    author_link: 'https://lisk.chat/direct/isabella',
    app_images: ['https://s3.amazonaws.com/awesome-files/liskHunt/liskjs.jpg'],
    app_link: 'https://lisk.io/download',
    app_id: 'liskjs',
  },
  {
    app_name: 'Lisk Blockchain Explorer',
    short_description: 'The official blockchain explorer for Lisk.',
    category: 'LiskOfficial',
    author: 'LiskHQ',
    author_link: 'https://lisk.chat/direct/isabella',
    app_images: [
      'https://s3.amazonaws.com/awesome-files/liskHunt/liskexplorer.jpg',
    ],
    app_link: 'https://explorer.lisk.io',
    app_id: 'liskexplorer',
  },
  {
    app_name: 'Lisk Docs',
    short_description: 'The official lisk documentation',
    category: 'LiskOfficial',
    author: 'LiskHQ',
    author_link: 'https://lisk.chat/direct/isabella',
    app_images: [
      'https://s3.amazonaws.com/awesome-files/liskHunt/liskdocs.jpg',
    ],
    app_link: 'https://docs.lisk.io/docs',
    app_id: 'liskdocs',
  },
  {
    app_name: 'LiskScripts',
    short_description: 'Useful scripts for the Lisk Delegate Server',
    category: 'Script',
    author: 'mrv777',
    author_link: 'https://lisk.chat/direct/mrv777',
    app_images: [
      'https://s3.amazonaws.com/awesome-files/liskHunt/liskscripts.jpg',
    ],
    app_link: 'https://lisk.io/download',
    app_id: 'liskscripts',
  },
  {
    app_name: 'SwiftyLisk',
    short_description: 'Blockchain functionalities wrapped in Swift',
    category: 'Script',
    author: 'LiskUser1234',
    author_link: 'https://lisk.chat/direct/LiskUser1234',
    app_images: [
      'https://s3.amazonaws.com/awesome-files/liskHunt/swiftlisk.jpg',
    ],
    app_link: 'https://github.com/LiskUser1234/SwiftyLiskd',
    app_id: 'swiftlisk',
  },
  {
    app_name: 'LiskApi',
    short_description: 'A smart wrapper for Lisk node APIs.',
    category: 'Script',
    author: 'dakk',
    author_link: 'https://lisk.chat/direct/dakk',
    app_images: ['https://s3.amazonaws.com/awesome-files/liskHunt/liskapi.jpg'],
    app_link: 'https://github.com/andreafspeziale/liskapi',
    app_id: 'liskapi',
  },
  {
    app_name: 'Liskitbot',
    short_description:
      'Explore the Lisk network retrieving information about your delegate',
    category: 'Bot',
    author: 'liskit',
    author_link: 'https://lisk.chat/direct/liskit',
    app_images: [
      'https://s3.amazonaws.com/awesome-files/liskHunt/liskitbot.jpg',
    ],
    app_link: 'https://github.com/andreafspeziale/liskitbot',
    app_id: 'liskitbot',
  },
  {
    app_name: 'always-forge',
    short_description: 'Fail-over forging script for Lisk',
    category: 'Script',
    author: '4miners',
    author_link: null,
    app_images: [
      'https://s3.amazonaws.com/awesome-files/liskHunt/alwaysforge.jpg',
    ],
    app_link: 'https://github.com/andreafspeziale/liskitbot',
    app_id: 'alwaysforge',
  },
];

export const labels = {
  Pool: 'is-primary',
  App: 'is-warning',
  Script: 'is-dark',
  Community: 'is-info',
  Bot: 'is-success',
  LiskOfficial: 'is-danger',
};
